# memory partitions/domains require CONFIG_USERSPACE
CONFIG_USERSPACE=y

# mpu configuration errors are only caught by an __ASSERT()
# if asserts aren't enabled, errors are silently discarded...
CONFIG_ASSERT=y

# repro code only works when gap filling is enabled...
# ...but I suspect a wider issue that exists regardless
# of the value of this option. Good enough for PoC.
CONFIG_MPU_GAP_FILLING=y
